### ISSUE TITLE
Calling VAF on received block

### ISSUE THREAD

**Issue by palmskog** [certichain/toychain#17]
To allow behavior consistent with PoW protocols such as Bitcoin, we need to call the `VAF` function when receiving a `BlockMsg`. The most straightforward solution to me appeared to be changing:
```
| BlockMsg b =>
  let: newBt := btExtend bt b in
  let: newPool := [seq t <- pool | txValid t (btChain newBt)] in
  let: ownHashes := dom newBt ++ [seq hashT t | t <- newPool] in
  pair (Node n prs newBt newPool) (emitBroadcast n prs (InvMsg ownHashes))
```
into:
```
| BlockMsg b =>
  if VAF (proof b) ts (btChain bt) (txs b) then
    let: newBt := btExtend bt b in
    let: newPool := [seq t <- pool | txValid t (btChain newBt)] in
    let: ownHashes := dom newBt ++ [seq hashT t | t <- newPool] in
    pair (Node n prs newBt newPool) (emitBroadcast n prs (InvMsg ownHashes))
  else
    pair st emitZero
```
in `Protocol.v`. 

However, this leads to problems in the proof of the key lemma `clique_inv_step`, whose type is defined in terms of the functions `blocksFor` and `msg_block`, which implicitly express that all sent blocks will be included in the forest in each node, regardless of whether `VAF` returns true or not.

A straightforward solution to me seems to be to change `msg_block` and `blocksFor` to the following:
```
Definition msg_block (msg : Message) (bt: BlockTree) (ts : Timestamp) : block :=    
if msg is BlockMsg b then
  if VAF (proof b) ts (btChain bt) (txs b) then b
  else GenesisBlock
else GenesisBlock.

Definition blocksFor n ms bt ts :=
  [seq msg_block (msg p) bt ts | p <- ms & dst p == n].
```
and to adjust `clique_inv` properly:
```
(* Relating global and local block-trees *)
   forall n', holds n' w (fun st => bt = foldl btExtend (blockTree st) (blocksFor n' (inFlightMsgs w) (blockTree st) ts))
```
However, I cannot see a way to prove `clique_inv_step` without making the outcome of `VAF` invariant in some way across timestamps. One way to accomplish this is to make `Timestamp` an `ordType` and adding an axiom saying that `VAF` is preserved under the ordering:
```
Axiom VAF_ord :
  forall (b : block) bc ts ts',
    ord ts ts' ->
    VAF (proof b) ts bc (txs b) -> 
    VAF (proof b) ts' bc (txs b).
```
That is, once `VAF` is true at some point, it continues to be true for future points in time. But I am unsure how this meshes with contemporary proof-of-stake protocols (Bitcoin doesn't care about timestamps). Could either of you comment @ilyasergey @dranov?

**Comment by dranov** [comment]
As far as I can tell, there are two separate issues here:

1. Where is the best in the code to put the `VAF` check?
2. To what extent does `VAF` actually need `ts` a) for Bitcoin and b) in the general case?

Some background: `VAF` is a method through which nodes can independently check whether some block they receive was created/minted in accordance with the rules of the protocol. The current invariant only holds when nodes behave honestly and only broadcast minted blocks for which `VAF` is true (implied by the definition of `system_step`) -- thus it is fine if other nodes don't check it. Obviously, this doesn't make sense for more realistic invariants. In a real setting, nodes would need to check `VAF` locally. Where should nodes perform this check?

**Where to place the `VAF` check?**

First, it doesn't actually make sense for the `VAF` check to be in `BlockMsg`. Remember that the network might arbitrarily reorder messages. Thus, for a block sequence like A->B->C, a node might receive A, and then receive C (before it receives B). In this situation, a Bitcoin node, for example, can't determine whether C is a valid block (i.e. mined in accordance with the rules of the protocol) before it receives B. There are multiple reasons for this. The most straightforward one is that the node cannot tell how many blocks there are between A and C (it actually can't even tell which block C eventually connects to; it doesn't know that it's A), and thus can't tell whether a difficulty adjustment has occured in the meantime. As such, the node has no way of telling whether the block's hash is less than the target difficulty (which is what Bitcoin's PoW checks).

The only time you can tell whether a block is valid (satisfies both `VAF` and `txValid`) is when you have the entirety of the chain that precedes it. Given this, it seems to me that the best place to do the `VAF` check is during the local computation of `btChain`, akin to the way we handle `txValid`. This raises the question of whether `ts` is actually needed.

With regards to timestamps, there is also the issue that Bitcoin nodes don't accept blocks with timestamps more than 2 hour in the future relative to their local clock. (This is why the Bitcoin client refuses to start if your computer's clock is more than ~3 hours off). This seems like a dodgy design choice to me, as it complicates reasoning about consensus, but it's what Bitcoin does. I am not sure whether Bitcoin just pretends it never received that block, or whether it keeps it in storage. That's something we should look into.

**Does `VAF` need `ts`?**

a) For Bitcoin, if it just drops blocks too far into the future (rather than keeping them in storage), it seems to me that we can simply remove `ts` from VAF.

b) For some proof-of-stake protocols, like Peercoin, the timestamp is indeed more central to the protocol, although my suspicion right now is that it can be removed from `VAF` there as well, if nodes have some other way of determining if blocks' timestamps are "reasonably close to the true time". I'll think about it and get back to you on that front.

**Comment by palmskog** [comment]
Closing this based on discussion in #18.
